package util

const (
	SystemHostName              = "system.host.name"
	SystemUpTime                = "started.time.seconds"
	SystemDiskUsedBytes         = "system.disk.used.bytes"
	SystemPhysicalProcessors    = "system.physical.processors"
	SystemCPUCores              = "system.cpu.cores"
	SystemLogicalProcessors     = "system.logical.processors"
	SystemRunningProcesses      = "system.running.processes"
	SystemOSVersion             = "system.os.name"
	SystemVendor                = "system.vendor"
	SystemSerialNumber          = "system.serial.number"
	SystemCPUIdlePercent        = "system.cpu.idle.percent"
	SystemMemoryFreePercent     = "system.memory.free.percent"
	SystemCacheMemoryBytes      = "system.cache.memory.bytes"
	SystemMemoryUsedPercent     = "system.memory.used.percent"
	SystemMemoryAvailableBytes  = "system.memory.available.bytes"
	SystemCPUDescription        = "system.cpu.description"
	SystemCPUInterruptPerSec    = "system.cpu.interrupt.per.sec"
	SystemMemoryCommittedBytes  = "system.memory.commited.bytes"
	SystemDiskFreePercent       = "system.disk.free.percent"
	SystemDiskUsedPercent       = "system.disk.used.percent"
	SystemNetworkTCPConnections = "system.network.tcp.connections"
	SystemContextSwitchesPerSec = "system.context.switches.per.sec"
	SystemDiskCapacityBytes     = "system.disk.capacity.bytes"
	SystemCPUType               = "system.cpu.type"
	SystemName                  = "system.name"
	SystemThreads               = "system.threads"
	SystemProcessorQueueLength  = "system.processor.queue.length"
	SystemCPUUserPercent        = "system.cpu.user.percent"
	SystemCPUPercent            = "system.cpu.percent"
	SystemMemoryInstalledBytes  = "system.memory.installed.bytes"
	SystemMemoryUsedBytes       = "system.memory.used.bytes"
	SystemDiskFreeBytes         = "system.disk.free.bytes"
	SystemMemoryFreeBytes       = "system.memory.free.bytes"
)
